### PR TITLE
构建系统修改为Gradle

### PR DESCRIPTION
**Pull request by huanmeng-qwq**
https://gradle.org/

Sync https://github.com/SNWCreations/KookBC/pull/106

### CODE REVIEW

**Review by SNWCreations — COMMENTED** [review]
OK, is JitPack artifact available?

**Comment by huanmeng-qwq** [comment]
https://javadoc.jitpack.io/com/github/SNWCreations/JKook/build~gradle-1446777373-1/index.html
https://jitpack.io/com/github/SNWCreations/JKook/build~gradle-1446777373-1/build.log

**Review by SNWCreations — APPROVED** [review]
OK

**Comment by SNWCreations** [comment]
Branch can be deleted

**Comment by SNWCreations** [comment]
Javadoc not available correctly, IDK if it is a JitPack fault.

**Pull request merged**
